---
title: "A little about me"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---


I'm a veterinarian by training and a second-year master's student in the department
of Epidemiology at the Mailman School of Public Health, Columbia University. My 
early clinical practice years were mainly focused on Farm animals medicine in my
home country, Egypt, before I moved to animal health pharmaceuticals and biologics,
then slowly found my way into One Health. My broad research interests are in the 
ecology and epidemiology of emerging zoonotic viruses in global hotspots with the
goal of understanding the drivers of infectious disease emergence particularly 
that of pathogenic viruses that cause outbreaks in both animal and human populations.
This research can serve as basis to develop One Health-oriented strategies and
interventions to prevent spillovers and future pandemics. My current research focus
on ecological factors associated with prevalence of paramyxpviruses in fruit bats in Bangladesh.

You can learn more about this area of research by visiting the
[EcoHealth Alliance](https://www.ecohealthalliance.org/) website where I currently 
do research.

Outside of academia, I love running and enjoy hiking particularly in state and national parks. 