---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%")
  
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Getting and tidying the data

```{r}
data("ny_noaa")

ny_noaa <-
  ny_noaa %>% 
  as_tibble(ny_noaa)

 ny_weather <-
  ny_noaa %>%
    separate(date, sep = "-", into = c("year", "month", "day")) %>% 
    mutate(
        across(.col = (c("year", "month", "day")), as.integer),
        snow = as.double(snow),
        tmax = as.double(tmax),
        tmin = as.double(tmin),
        month = month.name[month],
        tmax = tmax / 10,
        tmin = tmin / 10
        ) %>% 
    select(id, year, month, snow, tmax, tmin) %>% 
    filter(
        id %in% c("USW00094728", "USC00301625", "USC00303319", "USC00308944", 
                  "USC00304174","USC00309000", "USC00300343", "USC00304555",
                  "USC00300055", "USC00306649", "USC00307035"),
        year %in% c(2006:2010),
        month %in% c("November", "December", "January", "February", "March", "April")) %>% 
    drop_na()
```


## Plotting with plotly...

### scatterplot

```{r}
ny_weather %>%
    plot_ly(
        x = ~tmax,
        y = ~tmin,
        color = ~year,
        type = "scatter",
        mode = "markers",
        alpha = .7)
```


### Boxplot

```{r}
ny_weather %>%
    mutate(id = fct_reorder(id, tmax)) %>% 
    plot_ly(
        y = ~tmax,
        color = ~id,
        type = "box",
        colors = "viridis")
```


### Barplot

```{r}
ny_weather %>%
    count(id) %>% 
    mutate(id = fct_reorder(id, n)) %>% 
    plot_ly(
        x = ~id,
        y = ~n,
        type = "bar")
```


### ggplotly

```{r}
 noaa_scatterplot <-
    ny_noaa %>%
    separate(date, sep = "-", into = c("year", "month", "day")) %>% 
    mutate(
        across(.col = (c("year", "month", "day")), as.integer),
        snow = as.double(snow),
        tmax = as.double(tmax),
        tmin = as.double(tmin),
        month = month.name[month],
        tmax = tmax / 10,
        tmin = tmin / 10
        ) %>% 
    group_by(id, year, month) %>% 
    filter(month %in% c("January", "July")) %>% 
    drop_na() %>% 
    summarize(
        average_tmax = round(mean(tmax), 2)) %>% 
    ggplot(aes(x = year, y = average_tmax, color = id)) +
    geom_line(alpha = .5) +
    facet_grid(. ~ month) +
    theme(legend.position = "none") + 
    labs(
        title = "Average Maximum Temperature plot",
        x = "Year",
        y = "Average Maximum Temperature",
        caption = "Data from rnoaa") + 
    scale_x_continuous(
        breaks = c(1980, 1982, 1984, 1986, 1988, 1990,1992, 1994, 1996, 1998, 2000,
               2002, 2004, 2006, 2008, 2010)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

 ggplotly(noaa_scatterplot)
```

